# fly.toml app configuration file generated for fullstack-test on 2023-08-07T12:24:18+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-test"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
